# Generated by Django 4.0.10 on 2023-10-01 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='expiring_link',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
