# Generated by Django 4.0.10 on 2023-10-01 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_plan_expiring_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='core.plan'),
        ),
        migrations.AlterField(
            model_name='thumbnail',
            name='size',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
